### ISSUE TITLE
Feature request: Display favicon when generating PDF document

### ISSUE THREAD

**Issue by interlakedev** [phartenfeller/sveltekit-1.0-sqlite-demo-app#5]
Hello, please let me know if it's possible to display the website favicon when generating the PDF document. I have been trying to find a solution for Svelte RequestHandler and I haven't been successful.

Thanks!
John

![2023-08-14_09-18-00](https://github.com/phartenfeller/sveltekit-1.0-sqlite-demo-app/assets/88144726/ecfd8ad6-3934-495d-968c-e277bce09f7d)

**Comment by phartenfeller** [comment]
You could just load the pdf inside an iframe and have a normal svelte site around that.

**Comment by interlakedev** [comment]
Thank you for the helpful tip!
