### ISSUE TITLE
Breaks with latest vite-imagetools (6.2.3)

### ISSUE THREAD

**Issue by saschakrueger** [phartenfeller/sveltekit-1.0-sqlite-demo-app#6]
With the latest version of vite-imagetools 6.2.3 this demo breaks.
Is there any intention to make it compatible with the latest version?

**Comment by phartenfeller** [comment]
Hi! Unfortunately, I don't have the time to look into changes for every package. As the old version still works, I wouldn't say anything is broken.

If you like, you could look into the issue yourself and create a pull request with fixes.
